package model

import "github.com/globalsign/mgo/bson"

// participant student of the activity
type Admin struct {
	// id generated by mongo
	Id       bson.ObjectId `bson:"_id" json:"_id"`
	Name     string        `bson:"name" json:"name"`
	Password string        `bson:"password" json:"password"`
	Avatar   string        `bson:"avatar" json:"avatar"`
	Level    int           `bson:"level" json:"level"`
	// 存用户反馈的工单消息
	NotiList string `bson:"notiList" json:"notiList"`
}
