package model

import (
	"github.com/globalsign/mgo/bson"
	"time"
)

// 三种类型，全体通知，部分通知，以及用户反馈，所有的通知都会自动发送邮件
const (
	AdminAllNoti = iota
	AdminPartialNoti
	UserNoti
)

// 通知，包括管理员向用户发送的通知，以及用户提交的反馈
type Notification struct {
	// id generated by mongo
	Id bson.ObjectId `bson:"_id" json:"_id"`
	// 通知的类型
	Type int `bson:"type" json:"type"`
	// 通知的角色
	Pid string `bson:"pid" json:"pid"`
	// 通知的状态
	Alive bool `bson:"alive" json:"alive"`
	// 通知的等级（1-5），5为最重要
	Level int `bson:"level" json:"level"`
	// 通知的状态
	Title string `bson:"title" json:"title"`
	// 发送的时间
	Time time.Time `bson:"time" json:"time"`
	// 通知的内容
	Content string `bson:"content" json:"content"`
	// 发送的_id list
	IdList string `bson:"idList" json:"idList"`
}
