package model

import "github.com/globalsign/mgo/bson"

// participant student of the activity
type Participant struct {
	// id generated by mongo
	Id bson.ObjectId `bson:"_id" json:"_id"`
	// project id
	Pid string `bson:"pid" json:"pid"`
	// student card id
	Sid              string `bson:"sid" json:"sid"`
	Name             string `bson:"name" json:"name"`
	Gender           string `bson:"gender" json:"gender"`
	Email            string `bson:"email" json:"email"`
	Phone            string `bson:"phone" json:"phone"`
	Wechat           string `bson:"wechat" json:"wechat"`
	NativePlace      string `bson:"nativePlace" json:"nativePlace"`
	Height           float64 `bson:"height" json:"height"`
	Weight           float64 `bson:"weight" json:"weight"`
	Birthday         string `bson:"birthday" json:"birthday"`
	School           string `bson:"school" json:"school"`
	AcceptDiffSchool bool `bson:"acceptDiffSchool" json:"acceptDiffSchool"`
	Major            string `bson:"major" json:"major"`
	FuturePlace      string `bson:"futurePlace" json:"futurePlace"`
	HopeOther        string `bson:"hopeOther" json:"hopeOther"`
	Declaration           string `bson:"declaration" json:"declaration"`
	// stringfy的json，一些信息
	Desc string `bson:"desc" json:"desc"`
	// 可以修改的次数，默认是1次，需要额外修改次数的话需要向管理员发送请求
	ModifyTimes int `bson:"modifyTimes" json:"modifyTimes"`
	// 是否有匹配到的对象
	HasPair bool `bson:"hasPair" json:"hasPair"`
	// 匹配到的对象编号
	PairPid string `bson:"pairPid" json:"pairPid"`
	// 消息列表（只存部分通知，全局公告不算）
	//NotiList string `bson:"notiList" json:"notiList"`
	// 简历图片的url
	Resume string `bson:"resume" json:"resume"`
}

// 只有共享信息
type ParticipantPublic struct {
	// project id
	Pid string `bson:"pid" json:"pid"`
	Gender           string `bson:"gender" json:"gender"`
	NativePlace      string `bson:"nativePlace" json:"nativePlace"`
	Height           float64 `bson:"height" json:"height"`
	Weight           float64 `bson:"weight" json:"weight"`
	Birthday         string `bson:"birthday" json:"birthday"`
	School           string `bson:"school" json:"school"`
	AcceptDiffSchool bool `bson:"acceptDiffSchool" json:"acceptDiffSchool"`
	Major            string `bson:"major" json:"major"`
	FuturePlace      string `bson:"futurePlace" json:"futurePlace"`
	HopeOther        string `bson:"hopeOther" json:"hopeOther"`
	Declaration           string `bson:"declaration" json:"declaration"`
	// 是否有匹配到的对象
	HasPair bool `bson:"hasPair" json:"hasPair"`
	Resume string `bson:"resume" json:"resume"`
	//// 匹配到的对象编号
	//PairPid string `bson:"pairPid" json:"pairPid"`
}